apiVersion: v1
kind: Deployment
   annotations:
       meta.helm.sh/release-name: masu-backend
metadata:
  name: mas-app-user-deployment
  namespace: mass-app
  labels:
    name: user-deployment
spec:
  containers:
  - name: myapp
    image: 6345738929.kdr.ecr.eu-west-1.amazonaws.com/mas-web-app:v1
    resources:
      limits:
         cpu: 500m
         memory: 1000Mi
    requests:
       cpu: 200m
       memory: 250Mi
    ports:
      - containerPort: 8080
